[package]
name = "ypbank_tools"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "converter"
path = "src/main.rs"

[[bin]]
name = "comparer"
path = "src/bin/comparer.rs"

[lib]
name = "parser"
path = "src/lib.rs"
